language: groovy

groovy:
    - 2.3.6
    - 2.3.9

jdk:
    - oraclejdk8

install: true

script: ./gradlew -PpluginOnly=true clean build

after_success: ./gradlew -PpluginOnly=true jacocoTestReport coveralls

cache:
    directories:
        - $HOME/.gradle
        - $HOME/.m2